### ISSUE TITLE
Add mdbook-toc

### ISSUE THREAD

**Issue by igaray** [rust-lang/rustc-dev-guide#1014]
[mdbook-toc](https://github.com/badboy/mdbook-toc) is an mdbook preprocessor that allows auto-generating TOCs. This is useful for long sections with many subtitles.

- [x] Add the preprocessor configuration to `book.toml`
- [x] Add the preprocessor to the CI configuration
- [x] Add the preprocessor dependency and usage to the instructions on how to contribute to the guide.
- [x] Identify sections in need of a TOC and add the `<!-- toc -->` marker

**Comment by jyn514** [comment]
Related: https://github.com/rust-lang/rustc-dev-guide/issues/853
