### ISSUE TITLE
Add machine-readable dates to keep docs up-to-date

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustc-dev-guide#1018]
Is there someway to make the data references machine parseable? We could then write a simple tool to remind us when references are ~6 months old, and we should check it they’re still true.

_Originally posted by @rylev in https://github.com/rust-lang/rustc-dev-guide/issues/1013#issuecomment-757342522_

**Comment by camelid** [comment]
I suggested one way of doing it here: https://github.com/rust-lang/rustc-dev-guide/pull/1013#issuecomment-757400029

Another way is to use HTML comments like `<!-- date: 2021-01-10 -->`, which seems very feasible. Then we can add those comments to parts of the docs that say "As of now" or "As of January 2021" and then we can have a GitHub Action that automatically creates an issue after 6 months saying "Check in on this spot".

**Comment by jyn514** [comment]
We decided in [today's meeting](https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-rustc-dev-guide/topic/meeting.202021.2E01.2E13/near/222647082) that we should do this with a GitHub action that runs monthly and opens at most one issue with checkboxes for each section of the guide that's out of date (and preferably tag it with E-easy).

**Comment by camelid** [comment]
Status update:

I've been working on this, and I think it's almost done! :tada:
I'm not familiar with GitHub Actions beyond basic `cargo build` stuff, so I
think I'm going to test it on a private repo first to make sure it works.

I also had an idea for a way to make sure people use `<!-- date: 2021-01 -->`:
We add another GitHub Action as part of CI that looks for the phrase `as of now`
(case-insensitive and with varying whitespace of course) and fails CI if it
finds one. It then prints out a message to the logs or, better yet, posts a
comment that says something like:

> Please use the phrase `as of January 2021` instead of `as of now` since it
> makes it easier to determine if something is still true. Additionally,
> **please add a `<!-- date: 2021-01 -->` comment near the `as of January 2021`
> phrase** so that our automated system can pick it up. Thanks!

where `January 2021` and `2021-01` would be whatever the current month was.
I think this check could be implemented fairly easily. Maybe I can do it after I
finish the date-checker.

**Comment by rylev** [comment]
@camelid FYI: we're currently using TravisCI though there is an issue for switching to GitHub Actions #940

**Comment by camelid** [comment]
Yeah, I think it's better if new things are added to GitHub — plus it's easier since it seems GitHub Actions would have better integrations with GitHub, e.g. for opening issues ;)

**Comment by camelid** [comment]
I tested this on a private repo, and confirmed that it works! 🎉 

PR: #1037

**Comment by camelid** [comment]
Since it's February 3, and thus we missed the start of the month, and also to test it, I'm going to manually trigger a run of the date-checker now!

**Comment by camelid** [comment]
It worked! #1046
