### ISSUE TITLE
Fixed a typo in readme.md and corrected a hyperlink for MIR

### ISSUE THREAD

**Issue by saki-osive** [rust-lang/rustc-dev-guide#1021]
### Issue for the PR #1020 

This is an issue for the PR #1020 I have corrected the hyperlink for MIR in the page https://github.com/rust-lang/rustc-dev-guide/blob/master/src/part-5-intro.md

> So far, we've shown how the compiler can take raw source code in text format and transform it into ```MIR```. We have also shown how the compiler does various analyses on the code to detect things like type or lifetime errors. Now, we will finally take the MIR and produce some executable machine code.

The link that originally pointed to the highlighted ```MIR``` was incorrectly set to https://github.com/rust-lang/rustc-dev-guide/blob/master/src/mir/index.html. I have set it to https://github.com/rust-lang/rustc-dev-guide/blob/master/src/mir/index.md.

Plus, I have corrected a typo in the readme.md.

**Comment by camelid** [comment]
By the way, you don't need to open an issue for small PRs like this!

**Comment by saki-osive** [comment]
Okay, got it, thanks.
