### ISSUE TITLE
Where to find the doc of Span datatype?

### ISSUE THREAD

**Issue by VitalyAnkh** [rust-lang/rustc-dev-guide#1054]
The [glossary page](https://rustc-dev-guide.rust-lang.org/appendix/glossary.html#span) said:

"See the Span datatype for more."

But I can't find Span datatype in rust std document. Where should I go?

**Comment by LeSeulArtichaut** [comment]
The compiler is documented at https://doc.rust-lang.org/nightly/nightly-rustc/

Here's the Span documentation: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/struct.Span.html

**Comment by VitalyAnkh** [comment]
@LeSeulArtichaut Thanks! How about adding  this link( https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/struct.Span.htmlc)to "the Span datatype"?

**Comment by jyn514** [comment]
@VitalyAnkh sounds great! Are you interested in making a PR?

**Comment by VitalyAnkh** [comment]
@jyn514 Hi! It's a small edit and will conflict with [this PR](https://github.com/rust-lang/rustc-dev-guide/pull/1053 ) as a standalone PR, so I commit this edit in that PR.
