### ISSUE TITLE
Conflicting instructions for pushing new commits to PRs versus amending

### ISSUE THREAD

**Issue by not-an-aardvark** [rust-lang/rustc-dev-guide#1058]
I recently opened a [PR](https://github.com/rust-lang/rust/pull/82169), which was my first time contributing to the rust repo. The `rust-highfive` bot left a comment saying, "If any changes to this PR are deemed necessary, please add them as extra commits." I think I might have read this comment initially, but then I forgot about it.

Later, when I needed to make changes to the PR, I wasn't sure whether I should amend or push additional commits, so looked at [this documentation](https://rustc-dev-guide.rust-lang.org/contributing.html). It says, "please make sure that fixup commits are squashed into other related commits with meaningful commit messages.", which seems like the opposite of what the `rust-highfive` bot said. (In hindsight, I suspect maybe this is referring specifically to the the rebase process and not the process of adding fixup commits generally, but I'm only maybe 70% sure of this, and I still don't know what the recommended practice is.)

It seems like clarifying the documentation here could allow for a smoother process for future contributors/ensure that everyone is able to follow the recommended guidelines.

**Comment by camelid** [comment]
Looks like this is the same idea as #900. Do you want to close this and post your comment there?

**Comment by not-an-aardvark** [comment]
Yep, thanks for pointing that out.
