### ISSUE TITLE
Git "No-Merge Policy"

### ISSUE THREAD

**Issue by Gentoli** [rust-lang/rustc-dev-guide#1171]
I am not sure if I am following [this](https://github.com/rust-lang/rustc-dev-guide/blob/1b56b094728188d1970ef94e727b6c384ac98b7c/src/git.md#no-merge-policy) correctly.
It seems to suggest `rust-lang/rust` is using the squash and merge / fast-forward strategy. But looking at its history is not doing that.

**Comment by skade** [comment]
The guide specifically disallows merge commits _in PRs_. Those PRs are later merged and not fast-forwarded. Bors (our friendly bot) takes care of the merging. So you see all merges back into the main branch and who signed them off, but no merges of the main branch into PR branches.
