### ISSUE TITLE
'print this book' button doesn't work

### ISSUE THREAD

**Issue by OnlyLys** [rust-lang/rustc-dev-guide#118]
Hi, I believe the 'print this book' button in the top right corner of the documentation doesn't work. It only prints a screenshot of the current page instead of producing a concatenated document of all the pages in the book.

**Comment by steveklabnik** [comment]
I seem to get a whole page. This also may be an mdbook bug, not a rustc-guide bug.

**Comment by mark-i-m** [comment]
@Michael-F-Bryan Do you happen to know more about this?

**Comment by phansch** [comment]
This seems to happen at least in Firefox Nightly 61 and Firefox 59.0.2. (I printed to a PDF)
