### ISSUE TITLE
Document how/when to use diagnostic items

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rustc-dev-guide#1188]
Rustc has introduced diagnostic items to avoid using hard-coded paths to check for `std` and `core` types. However, there seems to be a lack of documentation regarding them. Here is a rough overview of what should be documented:

- How to find the diagnostic item for type XYZ
- How to add a new diagnostic item
  - Define diagnostic item naming conventions.
- How to use diagnostic items

See rust-lang/rust-clippy#5393 for more context and related discussions/links etc.

**Comment by xFrednet** [comment]
I'll start working on this. But it might take some time as I'm also busy with some RL stuff currently :upside_down_face:

**Comment by camelid** [comment]
Assigned you so that people know you're planning to work on it :)

**Comment by xFrednet** [comment]
Thank you!

**Comment by LeSeulArtichaut** [comment]
(`@rustbot claim` is enabled in this repo as well, in case you would want to work on something else in the future :upside_down_face:)
