### ISSUE TITLE
Section "Using pre-built LLVM" in "Adding a new target" does not work

### ISSUE THREAD

**Issue by piegamesde** [rust-lang/rustc-dev-guide#1251]
https://rustc-dev-guide.rust-lang.org/building/new-target.html#using-pre-built-llvm

I added

```
[target.x86_64-unknown-linux-gnu]
llvm-config = "/path/to/llvm/llvm-7.0.1/bin/llvm-config"
```

to my `./.cargo/config` and I then get the following error: "error: expected a table, but found a string for `target.x86_64-unknown-linux-gnu.llvm-config`"

**Comment by camelid** [comment]
@piegamesde You need to add that to your `config.toml` in `rust-lang/rust`:

> You can tell Rust to use a pre-built version of LLVM using the target section of `config.toml`:

**Comment by camelid** [comment]
Closing for now, please re-open if it still doesn't work when you add it to `config.toml`.

**Comment by piegamesde** [comment]
Oh wow I totally missed that. Thank you.
