### ISSUE TITLE
`cfg(bootstrap)` docs don't say what it does

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustc-dev-guide#1255]
https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html#why-does-only-libstd-use-cfgbootstrap

cc https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/rename.20.60cfg.28bootstrap.29.60.20to.20.60cfg.28stageN.29.60

**Comment by camelid** [comment]
It also misleadingly says that rustc only uses `cfg(bootstrap)` when adding internal lints for diagnostic items. That's not true; rustc also uses `cfg(bootstrap)` when feature gates that are used internally are renamed or removed

**Comment by jyn514** [comment]
The docs for `cfg(bootstrap)` are here: https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html#complications-of-bootstrapping. Maybe it would help to link there from the libstd section?

> It also misleadingly says that rustc only uses `cfg(bootstrap)` when adding internal lints for diagnostic items. That's not true; rustc also uses `cfg(bootstrap)` when feature gates that are used internally are renamed or removed.

👍 I'll fix this.
