### ISSUE TITLE
examples/rustc-driver-getting-diagnostics.rs doesn't work

### ISSUE THREAD

**Issue by tamaroning** [rust-lang/rustc-dev-guide#1263]
I followed [this page](https://rustc-dev-guide.rust-lang.org/rustc-driver-getting-diagnostics.html) and tried to compile the example. But couldn't.

In my environment, src/main.rs contains the same component as rustc-driver-getting-diagnostics.rs
```
pathot/test> cargo --version
cargo 1.52.0-nightly (90691f2bf 2021-03-16)
pathto/test> cargo r
   Compiling test_rs v0.1.0 (pathto/test)
error[E0308]: mismatched types
  --> src\main.rs:84:38
   |
84 |                 let _ = tcx.analysis(());
   |                                      ^^ expected enum `CrateNum`, found `()`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `test_rs`

To learn more, run the command again with --verbose.
pathto/test>
```

**Comment by tamaroning** [comment]
Oh, I found #1262 .
So I'm going to update documents.

**Comment by jyn514** [comment]
Yeah, the examples aren't guaranteed to work with old versions; the compiler can make breaking changes to the internal API whenever it likes.
