### ISSUE TITLE
Prerequisites page has link to nonexistent section of Suggested Workflows page

### ISSUE THREAD

**Issue by rlee287** [rust-lang/rustc-dev-guide#1278]
The prerequisites page states that

> Otherwise, you'll need LLVM installed and llvm-config in your path. See this section for more info.

Where "this section" is a link to https://rustc-dev-guide.rust-lang.org/building/suggested.html#skipping-llvm-build.

However, the Suggested Workflows page does not contain information on skipping the LLVM build. Can this link be corrected or removed?

(Incidentally, I'd like to know if it is possible to use the system LLVM instead of either building LLVM or downloading LLVM from Rust CI for building rustc. I wasn't able to find a definitive answer to this in the rustc-dev-guide.)

**Comment by ehuss** [comment]
Essentially you just need to set llvm-config in config.toml.

It looks like it was removed in #1030.   @jyn514 I think there are legitimate use cases for needing to use the system LLVM, and having some instructions won't hurt.

**Comment by jyn514** [comment]
Seems good! I won't have time to add it back for a while though.

**Comment by camelid** [comment]
I think I already re-added this section back in February. Is [this](https://rustc-dev-guide.rust-lang.org/building/new-target.html#using-pre-built-llvm) what you were looking for? (Added in 2d42cf7ba4b1eeb0c286caacf8ba8972efab76f2.)

**Comment by rlee287** [comment]
Looks (to me, at least, since this is the first time I'm building `rustc` myself) like this does have the relevant information, in which case the link I mentioned should be changed to point to this section instead.
