### ISSUE TITLE
Link to dataflow analysis related YouTube lectures is broken

### ISSUE THREAD

**Issue by su225** [rust-lang/rustc-dev-guide#1283]
> For those who prefer audiovisual learning, the Goethe University Frankfurt has published a series of short lectures on YouTube in English that are very approachable.

https://www.youtube.com/watch?v=NVBQSR_HdL0&list=PL_sGR8T76Y58l3Gck3ZwIIHLWEmXrOLV_&index=3

It shows "Video unavailable".

**Comment by spastorino** [comment]
I'm not sure if the videos are around somewhere else but or we either find them online and fix the link or just remove the link and suggestion altogether.
