### ISSUE TITLE
Problem rendering TOC

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rustc-dev-guide#1303]
https://github.com/rust-lang/rustc-dev-guide/commit/cb3fb942e3c357ef2f901a1963efde8a4e54776c added a TOC to this page: https://rustc-dev-guide.rust-lang.org/query.html. Locally, this worked fine, but currently it looks like this:

<img width="1042" alt="Screen Shot 2022-02-17 at 3 14 43 PM" src="https://user-images.githubusercontent.com/19642016/154571953-5abc8ea8-1bff-41a4-bb78-1bf4d3ba16c1.png">

**Comment by camelid** [comment]
What's weird also is that the last entry "External Links" is rendered correctly...

**Comment by camelid** [comment]
Ah, I think I have a fix (though I think this is still a bug in the toc tool we use, cc @igaray who knows more about that).
