### ISSUE TITLE
Windows prerequisite instructions install incorrect Python package

### ISSUE THREAD

**Issue by skippy10110** [rust-lang/rustc-dev-guide#1324]
I'm working on contributing to rust for the first time and was following the instructions here: https://rustc-dev-guide.rust-lang.org/building/prerequisites.html

This says to use "winget install python", but this will install "Introduction to Python Programming by GoLearningBus". I think the correct instruction should be "winget install Python.Python.3".

I assume this got messed up when the msstore source was added, and winget is now just picking an arbitrary python package. In light of that, it might be appropriate to change the cmake instruction to "winget install Kitware.CMake" as well.

**Comment by camelid** [comment]
cc @wesleywiser – I think you're knowledgeable about Rust and Windows?

**Comment by wesleywiser** [comment]
Yeah, changing the instructions to use the complete package names (`Python.Python.3` and `Kitware.CMake`) is the correct solution. 👍

**Comment by skippy10110** [comment]
Actually, I wonder if a -e (for --exact) should be thrown in there too, just to be extra sure. :)

```
winget install -e Python.Python.3
winget install -e Kitware.CMake
```

**Comment by camelid** [comment]
Can someone familiar with Windows open a PR to fix this? @skippy10110 would you like to?

**Comment by skippy10110** [comment]
I can do that up. I was distracted working on my first ever MCP and so I was being lazy not posting a PR myself. 🤣 I did end up just switching over to linux for dev since it seemed easier. (WSL rocks!)

**Comment by skippy10110** [comment]
I just posted a PR, but this is actually my first time doing that on GitHub. Let me know if I did anything wrong!

**Comment by camelid** [comment]
You did it correctly :)
