### ISSUE TITLE
Debugging support chapter is somewhat outdated

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rustc-dev-guide#1391]
The chapter at https://rustc-dev-guide.rust-lang.org/debugging-support-in-rustc.html has several things that I noticed were out-of-date. Some observations:

* The GDB fork hasn't been a thing for about 4 years now. I think that link and the mention that there is a fork could be removed.
* The LLDB fork also hasn't been a thing for about as long. It is not built in CI, so all the notes about macOS and such should be removed. I believe none of it was upstreamed, so I think all of this information about LLDB is old enough to not be valuable, and I would suggest removing it.
* I would remove the sections about shipping GDB and LLDB. I do not believe there are any plans to do this for the foreseeable future.

**Comment by tshepang** [comment]
@ehuss should "Code signing for LLDB debug server on macOS" also be removed

**Comment by ehuss** [comment]
I'm not sure how much to remove.  I would consider just putting a prominent notice on the LLDB section that this is outdated/historical information, and then it can be reworked once things move forward again.

The debugging working group has been very recently talking about what approach they will take with lldb integration. So things are very much in flux in that regard. 

> Curiously, what are other (CLI) debuggers people use for Rust code.

I think gdb, lldb, windbg, and cdb are all used.

One peculiarity of this chapter is that it does not discuss the wrappers at all. The prebuilt Rust packages (and rustup) includes wrappers (rust-gdb, rust-gdbgui, rust-lldb). These are shell-script wrappers that launch the corresponding debugger with Python-based visualizers for common Rust types.

**Comment by tshepang** [comment]
> I'm not sure how much to remove. I would consider just putting a prominent notice on the LLDB section that this is outdated/historical information, and then it can be reworked once things move forward again.

Will leave that in in #1393 then... the rest is gone.

**Comment by tshepang** [comment]
> One peculiarity of this chapter is that it does not discuss the wrappers at all. The prebuilt Rust packages (and rustup) includes wrappers (rust-gdb, rust-gdbgui, rust-lldb). These are shell-script wrappers that launch the corresponding debugger with Python-based visualizers for common Rust types.

It's based on a single talk, so did not even attempt to be any comprehensive.
