### ISSUE TITLE
The "Debugging support in the Rust compiler" chapter seems relevant for users rather than contributors

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rustc-dev-guide#1409]
_Originally posted by @rylev in https://github.com/rust-lang/rustc-dev-guide/pull/1406#pullrequestreview-1049224734_:

> This also seems correct though some of the information provided seems more relevant for *users* of Rust rather than those working on the Rust compiler.

Should we move this chapter somewhere or clarify how it's involved in hacking rustc?

**Comment by chenyukang** [comment]
Sounds great!

For deugging rustc we already has:
https://rustc-dev-guide.rust-lang.org/compiler-debugging.html#configuring-the-compiler

I want to debug rustc with GDB, and can not find enough information on it.
So I spent some time to make it work.
Issues comes from an old GDB version, https://github.com/rust-lang/rust/issues/60705#issuecomment-761602642.

I will try to make a PR to complement it.

**Comment by jieyouxu** [comment]
Triage: clarified in #1417.
