### ISSUE TITLE
Document how to cross-compile to targets with additional requirements

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rustc-dev-guide#1444]
https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html?highlight=platform#building-targets-for-cross-compilation

```
thread 'main' panicked at 'Target "wasm32-wasi" does not have a "wasi-root" key', compile.rs:268:17
```

I've also tried `x86_64-apple-darwin` and that fails because the gcc `-arch` flag doesn't exist on Linux.

**Comment by SUPERCILEX** [comment]
Sounds like the wasm stuff should work, but would need a wasi toolchain. That should be explained. It would also be a good idea to link here: https://rustc-dev-guide.rust-lang.org/tests/ci.html#using-ci-to-test. That's what I was actually looking for since it will let me test my change.

**Comment by jyn514** [comment]
This was already documented in https://github.com/rust-lang/rustc-dev-guide/pull/1405. Is there any way we can make this more clear?

**Comment by SUPERCILEX** [comment]
I don't remember the context, so I'll just re-file the issue if it comes up again.
