### ISSUE TITLE
"macro expansion"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-dev-guide#15]
Talk about where macro expansion happens. There is lots of other stuff we should cover here eventually:

- Hygiene
- Custom derive and procedural macros and how those work

cc @jseyfried -- can you help on elaborating the list of things that belong here?

**Comment by mark-i-m** [comment]
Started a simple chapter on macro expansion here: #26 

I don't know much about hygiene, custom derive, or procedural macros, but I can write about normal `macro_rules` expansion...

**Comment by mark-i-m** [comment]
cc @federicomenaquintero

**Comment by mark-i-m** [comment]
Ping @federicomenaquintero :)

Are you still interested in writing something up about hygiene or proc macros?

**Comment by federicomenaquintero** [comment]
I am!  Apologies for taking so long; I've been busy with librsvg.

Now that I'm porting gnome-class to syn 0.12, I'm getting a much more practical view of hygiene.  I'll write something soon.

**Comment by mark-i-m** [comment]
Thanks for the update!

**Comment by mark-i-m** [comment]
@federicomenaquintero ping

(sorry to bug you again)
