### ISSUE TITLE
Fix RA recommended configuration

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rustc-dev-guide#1516]
https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc

it mentions `stage0-sysroot`, more discussion https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/empty.20build.2F.24HOST.20directory

Is not clear what's the right suggestion

cc @jyn514

**Comment by jyn514** [comment]
This config is no longer maintained in the guide itself. The version in the rust-lang/rust repo has been fixed.
