### ISSUE TITLE
"Canonical queries" section doesn't explain canonical queries

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#1527]
https://rustc-dev-guide.rust-lang.org/traits/canonical-queries.html doesn't mention the word "canonical" once. It looks like the docs got deleted in https://github.com/rust-lang/rustc-dev-guide/pull/679. @crlf0710 do you have time to add these back? Canonicalization is important and still happens in rustc, not chalk.

https://github.com/rust-lang/rust/blob/e940f845be13ff37d4ba28df5f40d74e5b0895a0/compiler/rustc_trait_selection/src/traits/mod.rs#L103-L114

**Comment by spastorino** [comment]
cc @lcnr

**Comment by crlf0710** [comment]
Submitted #1532

**Comment by jyn514** [comment]
Thank you ❤️
