### ISSUE TITLE
No method `enter` on InferCtxtBuilder

### ISSUE THREAD

**Issue by mejrs** [rust-lang/rustc-dev-guide#1543]
see https://rustc-dev-guide.rust-lang.org/type-inference.html#creating-an-inference-context

This enter method was removed a while ago, but the documentation is still there

**Comment by fmease** [comment]
The `enter` method might have been moved to `InheritedBuilder`: [`InheritedBuilder::enter`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_typeck/inherited/struct.InheritedBuilder.html#method.enter) if I read things correctly.

**Comment by Nilstrieb** [comment]
```rust
tcx.infer_ctxt().enter(|infcx| {
    // Use the inference context `infcx` here.
})
```
is now used as
```rust
let infcx = tcx.infer_ctxt().build();
// Use the inference context `infcx` here.
```

**Comment by Nilstrieb** [comment]
It also doesn't have a lifetime anymore except for `'tcx`.
