### ISSUE TITLE
fail to compile the examples

### ISSUE THREAD

**Issue by gftea** [rust-lang/rustc-dev-guide#1556]
I tried to compile the examples below

```bash
rustup +nightly component add rust-src rustc-dev llvm-tools-preview
rustc +nightly rustc-driver-interacting-with-the-ast.rs 
```

I got below errors

```bash
error[E0433]: failed to resolve: could not find `DiagnosticOutput` in `rustc_session`
  --> rustc-driver-interacting-with-the-ast.rs:46:43
   |
46 |         diagnostic_output: rustc_session::DiagnosticOutput::Default,
   |                                           ^^^^^^^^^^^^^^^^ could not find `DiagnosticOutput` in `rustc_session`

error[E0560]: struct `rustc_interface::Config` has no field named `diagnostic_output`
  --> rustc-driver-interacting-with-the-ast.rs:46:9
   |
46 |         diagnostic_output: rustc_session::DiagnosticOutput::Default,
   |         ^^^^^^^^^^^^^^^^^ `rustc_interface::Config` does not have this field
   |
   = note: available fields are: `opts`, `crate_cfg`, `crate_check_cfg`, `input`, `input_path` ... and 9 others

error: aborting due to 2 previous errors

```

**Comment by JohnTitor** [comment]
As noted in https://rustc-dev-guide.rust-lang.org/rustc-driver-interacting-with-the-ast.html#getting-the-type-of-an-expression:
> To get the type of an expression, use the global_ctxt to get a TyCtxt. The following was tested with nightly-2022-06-05 (see [here](https://github.com/rust-lang/rustc-dev-guide/blob/master/examples/rustc-driver-interacting-with-the-ast.rs) for the complete example):

A PR is welcome to update the nightly version :)

**Comment by gftea** [comment]
`DiagnosticOutput`  is removed from `Config` by commit "641f8249f99b407af7e5376b098323926eab1696", 2 months ago

PR submitted
