### ISSUE TITLE
Mention of `TyKind::UnnormalizedProjectionTy` which no longer exists

### ISSUE THREAD

**Issue by fmease** [rust-lang/rustc-dev-guide#1558]
https://rust-lang.github.io/chalk/book/clauses/type_equality.html#placeholder-associated-types contains:

> In rustc, [placeholder projection types] correspond to the `TyKind::UnnormalizedProjectionTy` enum variant, declared in compiler/rustc_middle/src/ty/sty.rs.

Do they now correspond to `TyKind::Alias(AliasKind::Projection, AliasTy { … })`? If so, I can gladly open a PR to update the outdated reference.

**Comment by tshepang** [comment]
I found https://github.com/rust-lang/rust/pull/72150

**Comment by JohnTitor** [comment]
That book isn't hosted here but on https://github.com/rust-lang/chalk, please open an issue or submit a PR directly there! I cannot transfer the issue so am going to close instead.

**Comment by tshepang** [comment]
Also, to make it clear, the type is `TyKind::UnnormalizedProjection` (and not `TyKind::UnnormalizedProjectionTy`), and was removed from the codebase.
