### ISSUE TITLE
Can Place in MIR be static variable?

### ISSUE THREAD

**Issue by StevenJiang1110** [rust-lang/rustc-dev-guide#1589]
I learn from the [MIR data types](https://rustc-dev-guide.rust-lang.org/mir/index.html#mir-data-types) section that a `Place` can be static variable. 

<img width="1284" alt="截屏2023-02-08 10 58 54" src="https://user-images.githubusercontent.com/27764680/217417598-1138e663-fcb5-4fc3-b5a1-63f23431dc21.png">

But from the [doc](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Place.html), I can't see that `Place` can used to represent a static variable. Is the `rustc-dev-guide` outdated here? Further, the `Place` is a `struct` instead of an enum now, while `rustc-dev-guide` describe it as an enum.

**Comment by JohnTitor** [comment]
Yeah, https://github.com/rust-lang/rust/pull/67000 changed this, we have to reflect it.
