### ISSUE TITLE
Document how to use an alternative stage0 compiler

### ISSUE THREAD

**Issue by eggyal** [rust-lang/rustc-dev-guide#1592]
In the page on bootstrapping, the guide currently states:

https://github.com/rust-lang/rustc-dev-guide/blob/df5aee0e60f76e1e9b1b4ecf84a63aa8883465d8/src/building/bootstrapping.md?plain=1#L54-L59

...but I cannot find it documented anywhere (even using `x.py help` and searching through `config.toml.example`) *how* one configures `x.py` to use an alternative stage0 compiler.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/blob/4e163af1e5c6300ebf04a0e70a44ab0f379898e5/config.toml.example#L214-L224
