### ISSUE TITLE
Typo in "Debugging the compiler" chapter

### ISSUE THREAD

**Issue by mikysett** [rust-lang/rustc-dev-guide#1599]
The title have a repetition: "Getting the the error creation location"
[The paragraph in the documentation](https://rustc-dev-guide.rust-lang.org/compiler-debugging.html#getting-the-the-error-creation-location)

**Comment by tshepang** [comment]
just in case you were not aware, there is an edit button on the top-right of each page, where you could submit such fixes (and other improvements)
