### ISSUE TITLE
MIR basic_block should not be accessed via function

### ISSUE THREAD

**Issue by Hoblovski** [rust-lang/rustc-dev-guide#1626]
I'm reading the section on [Identifiers in the compiler](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/identifiers.md) and it claims
> [BasicBlock](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.BasicBlock.html) identifies a basic block. It points to an instance of [BasicBlockData](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.BasicBlockData.html), which can be retrieved by indexing into [Body::basic_blocks()](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Body.html#method.basic_blocks) (note that you must call a function; the field is private).

However as of March 2023, I see rust-lang/rust/master is no longer using the function `basic_block()`, but instead directly accessing the field ([yeah it's public now](https://github.com/rust-lang/rust/blob/master/compiler/rustc_middle/src/mir/mod.rs#L228)).

Am I missing anything or should we update this sentence? Thank you.

**Comment by JohnTitor** [comment]
Thanks for reporting!
You're right, the field is now public and the method has been removed, see https://github.com/rust-lang/rustc-dev-guide/pull/1631's description.
