### ISSUE TITLE
Windows bootstraping

### ISSUE THREAD

**Issue by peachkalemarsexpress** [rust-lang/rustc-dev-guide#1638]
Maybe I'm in the wrong place, but I don't know where else to go.

I have a need to build my [custom toolchain](https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html#clarification-of-build-commands-stdout), for x86_64-pc-windows_msvc. But I get the `thread 'main' panicked at 'shared linking to LLVM is not currently supported on x86_64-pc-windows-msvc', src\bootstrap\native.rs:162:13`. I looked at the code and saw that it won't work with windows. 

Am I wrong? If so, I will be glad if you tell me how I can do it.

**Comment by jyn514** [comment]
#t-infra/bootstrap on Zulip is a better place to ask.

What is your config.toml? If you've configured llvm to be linked dynamically, that won't work on Windows like the error says.

**Comment by jyn514** [comment]
I'm going to close this since it's not related to the dev guide, feel free to follow up on Zulip.
