### ISSUE TITLE
Make the section on squashing git commits easier to find

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#1675]
Right now, the table of contents looks like this:
![image](https://user-images.githubusercontent.com/23638587/232871166-dd440dc3-27bf-4471-aa90-d5fa0afc8eb0.png)

This is missing a couple useful things:
- The "Advanced Rebasing" section doesn't mention squashing. We should add a "Squash your commits" header.
- The "Troubleshooting git issues" section doesn't mention "failed to push some refs". We should move that into its own section so it's easier to find without having to go through the whole page front to back.

**Comment by zahash** [comment]
can i do this?

https://github.com/rust-lang/rustc-dev-guide/pull/1784
