### ISSUE TITLE
Debugging with CodeLLDB on windows hangs

### ISSUE THREAD

**Issue by everdrone** [rust-lang/rustc-dev-guide#1689]
Cannot seem to launch the codelldb to debug rustc on windows.

Everything is extremely slow (probably due to the 100GB+ build data)

It's just stuck. maybe I'm doing something wrong?

Here's my config.toml
```toml
# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[rust]
debug = true
debuginfo-level = 2
```

```
python .\x.py build compiler --build=x86_64-pc-windows-msvc
```

System specs
Windows 11
AMD Ryzen 9 7950x

**Comment by jieyouxu** [comment]
Triage: if this is still relevant, please ask over at the compiler team zulip channel https://rust-lang.zulipchat.com/#narrow/channel/182449-t-compiler.2Fhelp as this repo is mostly for dev docs and is not actively watched by compiler team members, or open a new issue over at <https://github.com/rust-lang/rust>.
