### ISSUE TITLE
"HIR and HIR Lowering"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-dev-guide#17]
Talk about the HIR:

- [ ] how it is structured,
- [x] how to dump it and inspect it, 
- [x] the code that creates it (#148)
- [x] the HIR map

**Comment by theotherphil** [comment]
@nicomatsakis I'd like to give this a go, but know very little about compilers in general or rustc in particular. I'm happy to just read the code and put a rough first sketch together, but if you can point me at any other existing resources that would be great.

**Comment by nikomatsakis** [comment]
@theotherphil my plan is to move README content into the guide, since the guide itself will eventually move into rustc. Our experience has been that the READMEs are not typically very "discoverable". So, an initial PR based on the README would be a good start!

Feel free to ping me with questions. I'll try to keep up here, but you can also find me on gitter or IRC.

**Comment by theotherphil** [comment]
Ok great, thanks!

**Comment by mark-i-m** [comment]
Ping @theotherphil :)

Any updates?

**Comment by theotherphil** [comment]
Nothing yet, apart from copying Nico's README from librustc. I have a document with some questions I want to answer but I've not yet had time to work out any answers.

**Comment by theotherphil** [comment]
I didn't get the time to write anything useful on this topic and I'm now going to be computerless for a while so won't be doing any work in the near future either. Sorry for the slow progress - if anyone else fancies working on this they won't be stepping on my toes.

**Comment by mark-i-m** [comment]
Thanks for the heads up @theotherphil :)

**Comment by rylev** [comment]
Triage: closing. There is now a section on the HIR and HIR lowering so this issue is a bit too general. Closing this in favor of more specific issues.
