### ISSUE TITLE
Use ./x instead of ./x.py in documentation

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#1707]
`./x` is the most likely to work on every system (on Unix it runs the shell script that does python version detection, on Windows it will *probably* run the powershell script - certainly less likely to break than `./x.py` which often just opens the file in an editor).

This can be done with a simple find and replace, so it's a great first issue.

https://github.com/rust-lang/rustc-dev-guide/pull/1701#issue-1772868957

**Comment by sslime336** [comment]
@jyn514 Hi, I'd like to do this :-) but I also found that in nushell using vscode on Win10 that typing `./x` still just open the `x.py`, which acts like below:

![图片](https://github.com/rust-lang/rustc-dev-guide/assets/97684920/c3b33ceb-735e-4183-b8ea-0cd3f61438ea)

If it's ok, I will also doc the exception which comes from myself

**Comment by jyn514** [comment]
sounds good :) yes unfortunately there's nothing that's going to work on every platform, but i think `./x` has a better chance of working than `./x.py`.

**Comment by JohnTitor** [comment]
Addressed by #1710
