### ISSUE TITLE
Explain how to benchmark the compiler

### ISSUE THREAD

**Issue by orium** [rust-lang/rustc-dev-guide#175]

**Comment by mark-i-m** [comment]
@nnethercote @wesleywiser Would either of you be able to write something for this?

**Comment by nnethercote** [comment]
https://github.com/rust-lang-nursery/rustc-perf/blob/master/collector/README.md pretty much has this information. Maybe the guide should just point to that document?

**Comment by rylev** [comment]
Triage: Closing. This section already exists. It's not perfect, but we have other issues like #1150 that provide tracking for more specific issues.
