### ISSUE TITLE
region name resolution, early vs late bound lifetimes

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-dev-guide#177]
It'd be nice to make this concept obsolete someday. *Until then*, here is some discussion from Discord on the topic:

[region name resolution](https://discordapp.com/channels/442252698964721669/443113264751181824/476838477770784768), [early vs late](https://discordapp.com/channels/442252698964721669/443113264751181824/476839507983859727)

**Comment by mark-i-m** [comment]
I came across this: https://gist.github.com/nikomatsakis/fe440aec437f7e8ad4cce8319954a973
and the related discussion: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/reintegrating.20chalk.20into.20rustc/near/190518417

Would be good to include the info about early/late bound generics and why the difference exists.

cc @nikomatsakis @jackh726 #177

(Also, @nikomatsakis discord links break quite easily, so in future it would be great if you copy into a messy gist or hackmd and link that instead, sorry).

**Comment by nikomatsakis** [comment]
Hmm, I didn't know that Discord links break easily! Maybe I'll go back to my UUID technique of making links. =) (Embed a UUID one can search for)
