### ISSUE TITLE
Link to Visitor example 

### ISSUE THREAD

**Issue by dianestephens** [rust-lang/rustc-dev-guide#1799]
The MIR Visitor document does not have the link to the LocalUseVisitor example that counts how many times each local is used. -  "A very simple example of a visitor can be found in ...".  Would like to see an example here. https://rustc-dev-guide.rust-lang.org/mir/visitor.html

**Comment by marxin** [comment]
Should be fixed in #2017.
@tshepang Can you please close this issue?
