### ISSUE TITLE
document MIR-based borrowck

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-dev-guide#180]
So much to talk about here!

Off the top of my head:

- Dataflow
  - MovePathIndex and that whole setup
- The MIR typeck
- Liveness
- Regions and SCC
- The outlives constraint

**Comment by mark-i-m** [comment]
@nikomatsakis I think almost everything here is in the guide or in the TODOs. Do you want to keep this open?

**Comment by mark-i-m** [comment]
I'm going to go ahead and close this, as much of it is already documented. Please feel free to reopen or file a new issue if something is missing.
