### ISSUE TITLE
Dead links to docs (borrowcheck)

### ISSUE THREAD

**Issue by jdupak** [rust-lang/rustc-dev-guide#1819]
In https://rustc-dev-guide.rust-lang.org/borrow_check.html all the links to some subpaths of https://doc.rust-lang.org/nightly/nightly-rustc/rustc_borrowck/ are dead.

**Comment by ehuss** [comment]
There was an issue generating the docs. It should be fixed tomorrow via https://github.com/rust-lang/rust/pull/117535.

**Comment by JohnTitor** [comment]
Thank you both for reporting and providing the context!
Closing as there's nothing to do here.
