### ISSUE TITLE
Mistake link in Overview section for MIR

### ISSUE THREAD

**Issue by cocodery** [rust-lang/rustc-dev-guide#1827]
In [Overview](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/overview.md), you can see the link of `[High-Level Intermediate Representation (HIR)]` and `[Mid-level Intermediate Representation (MIR)]` in `HIR lowering` part and `MIR lowering` part separately.
They are not matched. `lowered to` is not nessceary for `MIR` maybe.
It's a small miktake, also you can ignore it.
![1](https://github.com/rust-lang/rustc-dev-guide/assets/89212840/7103a9a9-d5e5-4c63-9cba-946b0ab140cb)

**Comment by jieyouxu** [comment]
Triage: doesn't seem like a mistake to me.
