### ISSUE TITLE
Getting Started page "help-wanted-search" link goes to a 404 Github page

### ISSUE THREAD

**Issue by Mathys-Gasnier** [rust-lang/rustc-dev-guide#1854]
Hi, in [Getting Started](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/getting-started.md) the [help-wanted-search link](https://github.com/rust-lang/rustc-dev-guide/blob/1dc1152ccc9e631f3828586309427a1cecf5d076/src/getting-started.md?plain=1#L92C2-L92C20) goes to a 404 Github page.

I think the link is missing the repo owner and repo name in the URL ?

**Comment by spastorino** [comment]
This works fine for me, maybe it was fixed after you've opened this issue?.

**Comment by Mathys-Gasnier** [comment]
It also works for me, i don't see any commit changing the link, i'm lost, it didn't work on chrome, nor firefox last week, and now it's working... Weird but i guess i can close this
