### ISSUE TITLE
Clarify what is a UI test

### ISSUE THREAD

**Issue by Arthur-Milchior** [rust-lang/rustc-dev-guide#1861]
>  These are used in ui tests to test whether the expected set of paths exist in the dependency graph.

is found in https://rustc-dev-guide.rust-lang.org/incrcomp-debugging.html

Either UI means User Interface, and I would suggest you clarify how user interfaces are related to this compiler bug.

Or UI means something that is entirely different, and that seems harder to find by searching online for "UI test" or "UI rust", as most answer are related to user interface.

**Comment by ChrisDenton** [comment]
This is documented in the testing section. E.g. https://rustc-dev-guide.rust-lang.org/tests/ui.html#introduction

The one line summary in https://rustc-dev-guide.rust-lang.org/tests/compiletest.html states it like so:

> [ui](https://rustc-dev-guide.rust-lang.org/tests/ui.html) — tests that check the stdout/stderr from the compilation and/or running the resulting executable

**Comment by Arthur-Milchior** [comment]
Thank you. I fear in the meantime I forgot about it. 
May I suggest just adding a link on `ui` to this page?

**Comment by ChrisDenton** [comment]
Yes, adding a link would make sense. Would you be willing to make a pull request?

**Comment by Arthur-Milchior** [comment]
Already done https://github.com/rust-lang/rustc-dev-guide/pull/1862
