### ISSUE TITLE
Document IDE Setup

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rustc-dev-guide#198]
Basically, a chapter (appendix?) showing how common IDEs are set up to work on the Rust compiler.

**Comment by mark-i-m** [comment]
Personally, I use straight vim with racer/YouCompleteMe for completions (which only work sometimes...).

**Comment by jyn514** [comment]
Done in https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc.
