### ISSUE TITLE
Document compatibility and breakage policies

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-dev-guide#202]
Specifically, today has very strong stability promises. We should document how that fits in with crater, editions, bug fixes, and seemingly trivial changes with no apparent breakage.

cc @Centril

**Comment by Centril** [comment]
I don't think we have a coherent policy here; it's more a case-by-case basis.
For the `?` stuff we did edition breakage (zero crater regressions), for `if let` we did all-editions breakage (zero crater regressions), for `try` we did edition breakage (some cases were found in sourcegraph), etc.

cc @nikomatsakis @eddyb

**Comment by rylev** [comment]
I'm going to close this as it's a policy issue, and should most likely live in forge.

**Comment by camelid** [comment]
> https://forge.rust-lang.org/rustc-bug-fix-procedure.html

> Triage: Closing. This is a policy issue, and it should most likely live in forge not here.

Hmm, that Forge link now redirects to the rustc-dev-guide. Should it be moved to Forge?
