### ISSUE TITLE
Document how x.py works

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-dev-guide#248]
https://internals.rust-lang.org/t/compiling-rustc-with-non-standard-flags/8950/3

**Comment by jyn514** [comment]
@mark-i-m do you think https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html answers this well enough? Or was there something more you wanted to document?

**Comment by mark-i-m** [comment]
I think my intent was more related to how x.py is implemented and how to hack on it...

**Comment by jyn514** [comment]
Hmm, maybe I could link to https://github.com/rust-lang/rust/blob/master/src/bootstrap/README.md#extending-rustbuild in https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html#contributing-to-bootstrap.

**Comment by mark-i-m** [comment]
Perhaps? Or else move that readme to a short chapter in the guide. Not sure...

**Comment by jyn514** [comment]
@Mark-Simulacrum do you have opinions on whether this should be documented in the dev-guide or in-tree?

**Comment by Mark-Simulacrum** [comment]
Open to either; rustc-dev-guide is somewhat less likely to receive updates. x.py is not *that* complicated itself, just is incredibly stateful (filesystem), so that pretty significantly increases complexity of changing it. Not sure what kind of docs are intended here.

**Comment by jyn514** [comment]
This looks roughly the same as https://github.com/rust-lang/rust/issues/90686 to me; I'm going to close it since the other issue was also closed (the documentation now lives in-tree in src/bootstrap/README.md).

Happy to add more docs but I think we should use a more specific issue for that.
