### ISSUE TITLE
https://llvm.org/ link checks fail on travis

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rustc-dev-guide#265]
I'm assuming it's some sort of rate limiting or general overload protection on their side. Maybe we should just whitelist it?

**Comment by mark-i-m** [comment]
There were also some failures a while back with the ACM digital library #249. And I saw a few with a link to discord.gg. They always seem to be transient...

**Comment by shepmaster** [comment]
In a magical world, the tests could allow small amounts of errors in a time period, but warn if there's a consistent pattern. Sounds hard though.

**Comment by mark-i-m** [comment]
This has been happening a bit more frequently as we add more links. Sometimes it is actually the remote responding slowly (e.g. its slow from my browser too), but I think usually it is travis throttling us or something...

**Comment by mark-i-m** [comment]
We haven't had as many problems with this since adopting mdbook-linkcheck's new caching scheme, so I will go ahead and close this.
