### ISSUE TITLE
Reusing a built LLVM (e.g with git worktrees)

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/rustc-dev-guide#276]
Creating a new git worktree (or full clone) of Rust requires rebuilding LLVM, which takes "forever".

Should the guide include tips on how to mitigate this?  What are established rustc hackers doing to avoid this overhead?

**Comment by mark-i-m** [comment]
cc https://github.com/rust-lang/rustc-guide/issues/71

**Comment by mark-i-m** [comment]
Personally, I've been just rebuilding LLVM... it's a pain, but it only happens the first time I create the worktree...

**Comment by phansch** [comment]
I think this issue can be closed as it's documented here now: https://rustc-dev-guide.rust-lang.org/building/suggested.html?highlight=llvm#building-with-system-llvm
