### ISSUE TITLE
Terms used before being explained

### ISSUE THREAD

**Issue by Nashenas88** [rust-lang/rustc-dev-guide#418]
One example is Section 2.3:
DefId is brought up without explaining what it is. In the same section, tcx is brought up (and explained quickly as Type Context). A link to the glossary entry or the section "Identifiers in the HIR" on https://rust-lang.github.io/rustc-guide/hir.html would be helpful too.

**Comment by spastorino** [comment]
Agreed, maybe whenever a concept that is in the glossary shows up we can add a link to that section?.

**Comment by Nashenas88** [comment]
Yes, I think so. See my comment in the glossary issue here: https://github.com/rust-lang/rustc-guide/issues/420#issuecomment-521501587
