### ISSUE TITLE
Make HIR identifiers table more discoverable

### ISSUE THREAD

**Issue by Nashenas88** [rust-lang/rustc-dev-guide#420]
On https://rust-lang.github.io/rustc-guide/hir.html when I came across the list in the section "Identifiers in the HIR", I instantly wished I had seen it earlier in the book. It made a lot of earlier details easier to understand. It would have also been helpful if descriptions like this were available in the glossary.

**Comment by spastorino** [comment]
I guess you're talking about this https://rust-lang.github.io/rustc-guide/hir.html#identifiers-in-the-hir right?. `DefId` and `HirId` are already in the glossary, what you mean is to add `NodeId` and `BodyId`?

**Comment by Nashenas88** [comment]
`NodeId` is already there, but it would be helpful to add `BodyId`. However, I was more referring to the fact that the explanations in the link above are much easier to understand than the simple sentences in the glossary. Having a link from the glossary to those extended explanations would be really helpful, I think. I'm a big fan of bidirectional linking in documentation.

**Comment by Nashenas88** [comment]
For example, this is the existing entry for `DefId` in the glossary:
> `DefId` | an index identifying a definition (see `librustc/hir/def_id.rs`). Uniquely identifies a `DefPath`.

compared to the chart in the hir page:

> [DefId](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/def_id/struct.DefId.html), which primarily names "definitions" or top-level items.
>  - You can think of a [DefId](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/def_id/struct.DefId.html) as being shorthand for a very explicit and complete path, like `std::collections::HashMap`. However, these paths are able to name things that are not nameable in normal Rust (e.g. impls), and they also include extra information about the crate (such as its version number, as two versions of the same crate can co-exist).
> - A [DefId](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/def_id/struct.DefId.html) really consists of two parts, a `CrateNum` (which identifies the crate) and a `DefIndex` (which indexes into a list of items that is maintained per crate).

If every instance of `DefId` linked to the glossary, and the glossary linked to the more detailed description, it would allow people to easily find this very helpful explanation. Or would it make more sense to expand the description in the glossary so it's as helpful as the initial entry? Maybe also include a link in the glossary to the implementation in the source as the hir page documentation does?

**Comment by spastorino** [comment]
> `NodeId` is already there, but it would be helpful to add `BodyId`. However, I was more referring to the fact that the explanations in the link above are much easier to understand than the simple sentences in the glossary. Having a link from the glossary to those extended explanations would be really helpful, I think. I'm a big fan of bidirectional linking in documentation.
Agree with this really. Please provide a PR if you can/want :).

**Comment by AkechiShiro** [comment]
Hi, I have seen that [`BodyId`](https://rustc-dev-guide.rust-lang.org/hir.html) has been added also some explanations have changed, I don't know if this issue should still be open.
