### ISSUE TITLE
Introduce something about rmeta and metadata in general

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rustc-dev-guide#468]

**Comment by mark-i-m** [comment]
@crlf0710 I don't actually know anything about rmeta or metadata. Who even is the expert? Is there at least a code snippet you can point us to?

**Comment by crlf0710** [comment]
@mark-i-m Sure, there's the crate `src/librustc_metadata` in tree. For the experts part, i guess @eddyb @petrochenkov can say a lot on this topic.

**Comment by eddyb** [comment]
Btw, this is one of those areas I'd prefer refactoring into irrelevance - see https://github.com/rust-lang/rust/issues/65407.

**Comment by crlf0710** [comment]
@eddyb i believe metadata is the key to https://github.com/rust-lang/rust/issues/65427, do you think this issue is worth resolving before the refactoring you mentioned, or are they orthogonal?

**Comment by eddyb** [comment]
I think they're unrelated, talk to Cargo people (e.g. @alexcrichton and @ehuss) about how pipelining works for `cargo build` and how it relies on `.rmeta`s for almost the entire compilation (except `bin`/`staticlib`/`cdylib` crates, which do the actual linking and need `.rlib`s).

But also, even without reusing the `.rmeta`s, you could make Cargo use the same incremental directory between `cargo check` and `cargo build` and that "should just work".

**Comment by crlf0710** [comment]
@eddyb ok thanks! 

Is it possible when you have time to give some brief introduction (in text, audio or whatever form) about the current status (or if the current status is not ideal, a sketch of new design) of crate metadata storage on disk and the metadata embedded into final rlib/dylib files. I'm eager to learn more about this, and it will be good include it as part of rustc-guide.

**Comment by ehuss** [comment]
I went ahead and wrote something up in #1044 on this.  I realize things change over time, but I think a little information is useful.  If anyone following this issue can give it a read, please let me know if anything is missing you'd like to see (or if you notice anything wrong).
