### ISSUE TITLE
rename to rustc-dev-guide

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-dev-guide#470]
I propose we rename this repo to the rustc-dev-guide, to avoid confusion with the "rustc book" (and maybe we ought to rename *that* to the "rustc user's manual" or something, but that's a separate topic).

cc @rust-lang/compiler @rust-lang/wg-learning

**Comment by mark-i-m** [comment]
Alas, users strike again. I've always felt computer science would be way more fun if we had no users...

**Comment by nikomatsakis** [comment]
Does anyone know -- if I rename the repo, will links to the rendered format also redirect?

**Comment by eddyb** [comment]
All `github.com` links will redirect but `github.io` ones won't.

**Comment by mark-i-m** [comment]
Yes, github will redirect the links.

We should fix the following links in the book, though:
```console
$ rg github.io/rustc-guide
README.md
6:[You can read the latest version of the guide here.](https://rust-lang.github.io/rustc-guide/)

src/important-links.md
14:[link](https://rust-lang.github.io/rustc-guide/stabilization_guide.html)
15:[link](https://rust-lang.github.io/rustc-guide/stabilization_guide.html#updating-documentation)
16:[link](https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs)

src/implementing_new_features.md
181:[here]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html

src/tests/running.md
126:[mode]: https://rust-lang.github.io/rustc-guide/tests/adding.html#tests-that-do-not-result-in-compile-errors
```

Additionally, we will probably have broken links in the rust-lang/rust and rust-lang/forge repos in some readmes, I think...

**Comment by michaelwoerister** [comment]
👍 for renaming.

**Comment by mark-i-m** [comment]
I'm generally against renaming, as I think it will cause a lot of headaches. IMHO, those in favor of renaming should find the links that are going to break and make a list so that we can fix them.

**Comment by tshepang** [comment]
Should we worry about anything outside https://github.com/search?q=org%3Arust-lang+rust-lang.github.io%2Frustc-guide&type=Code?

**Comment by mark-i-m** [comment]
@tshepang Perhaps we make the old address redirect to the new one or add a link like "are you looking for the rustc-dev-guide? Click here"

**Comment by mark-i-m** [comment]
And we should maybe make a blog post

**Comment by tshepang** [comment]
@mark-i-m if that's all the links we care for, won't we get redirects for free, then fix such links at our leisure?

**Comment by mark-i-m** [comment]
@tshepang No I don't think so. TMK, Github only redirects links under github.com, not GitHub pages. That's why the forge has a manual list of redirects...

**Comment by pnkfelix** [comment]
If we are trying to address subtle differences in names, maybe we should spell out “rust compiler dev guide” rather than rely on the single letter “c” for the distinction between “Rust development” and “rustc development”?

**Comment by RalfJung** [comment]
FWIW, I feel like enough of these links are already spread across codebases, issues and bookmarks that redirects should be set up.

**Comment by mark-i-m** [comment]
Agreed. It's probably worth putting up a site that gives the user an option between the compiler guide and rustc-dev-guide...

**Comment by chrissimpkins** [comment]
> FWIW, I feel like enough of these links are already spread across codebases, issues and bookmarks that redirects should be set up.

@RalfJung We added this to the [transition plans](https://github.com/rust-lang/rustc-guide/issues/602).  We are planning to make the transition on Monday.  We still need to identify someone who can rename the rustc-guide repository to rustc-dev-guide and set up a new rustc-guide repository for the redirects.

**Comment by mark-i-m** [comment]
@chrissimpkins One other thing... it's probably worth making announcements on internals and Inside Rust blog about the transition...

**Comment by chrissimpkins** [comment]
> One other thing... it's probably worth making announcements on internals and Inside Rust blog about the transition...

Thanks @mark-i-m.  I added both as tasks in our list.  Will do!

**Comment by spastorino** [comment]
The guide was renamed. Tracking issue https://github.com/rust-lang/rustc-dev-guide/issues/602 for more context.
