### ISSUE TITLE
Document restrictions around `#[cfg(bootstrap)]`

### ISSUE THREAD

**Issue by anp** [rust-lang/rustc-dev-guide#552]
Based on https://github.com/rust-lang/rust/pull/67137#discussion_r362704411 I think there are likely a bunch of important things worth documenting around the use of `#[cfg(bootstrap)]`. The ones I can think of off the top of my head:

* Should only be used in libcore/libstd, not in the compiler
* Should not be used inside macros, as it leaks non-configurable elements of the standard library's macros as configurable by user-build flags, since the macro is expanded in user code
* Should apply to the smallest reasonable portion of the affected code

Any others?

**Comment by Mark-Simulacrum** [comment]
I think the first isn't quite right, it's fine to have cfg(bootstrap) in the compiler. What's not acceptable is having it in submodules (or other code that is not directly editable in-tree).

**Comment by anp** [comment]
Ah, that was told to me by @eddyb. I'll let them clarify what they meant then.

**Comment by jieyouxu** [comment]
Triage: `cfg(not(bootstrap))` documented in https://rustc-dev-guide.rust-lang.org/building/bootstrapping/what-bootstrapping-does.html?highlight=cfg(not(bootstrap))#complications-of-bootstrapping and `cfg(bootstrap)` in https://rustc-dev-guide.rust-lang.org/building/bootstrapping/what-bootstrapping-does.html?highlight=cfg(b#why-does-only-libstd-use-cfgbootstrap.
