### ISSUE TITLE
Commit copies of papers?

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-dev-guide#558]
Yeah, papers' links are quite fragile (not found, bad connection, etc.) so it's pain not only here but also on rustc CI. We should store the PDFs? I think it's worth to open the issue to decide how we deal with them.

_Originally posted by @JohnTitor in https://github.com/rust-lang/rustc-guide/pull/557_

**Comment by JohnTitor** [comment]
I'm not sure having copies are legal for license/copyright though, it's delicate I guess. Or it's enough to exclude specific links? (yeah, it's a hassle, I know.)

**Comment by spastorino** [comment]
Can't we tag certain links and have them giving warnings instead of hard errors?. So most of the links will fail in the situations described but we can tag links to papers in the ones we consider fragile in some way and have our system just giving warnings.

**Comment by spastorino** [comment]
Saw we have an exclude attribute on linkchecker, maybe we can change it with warn and make all the checks to those that fail give us a warning.

**Comment by mark-i-m** [comment]
Honestly, I don't think anyone will look at the warnings. I would prefer we just blacklist them....

**Comment by JohnTitor** [comment]
Or it'd be also nice that we check the status code then ignore any failures other than 404.

**Comment by JOE1994** [comment]
Could using links to *ACM* or *IEEE* also be an option?
Links to *ACM* or *IEEE* are usually quite stable.

ex)
https://web.njit.edu/~dingxn/papers/BWS.pdf
=>   https://dl.acm.org/doi/abs/10.1145/2168836.2168873

**Comment by mark-i-m** [comment]
@JOE1994 That's definitely an option, but we don't link check links to ACM DL because they tend to produce failures... still I don't think we expect those links to every really fail, so maybe we don't need to check them?

**Comment by mark-i-m** [comment]
Actually, I'm coming around to the position that linking to ACM DL or IEEE Explore when possible would be preferable -- though I don't think all of the linked documents are in ACM or IEEE.

**Comment by mark-i-m** [comment]
We haven't seen this in a while, so I'm going to go ahead and close the issue. It seems like linking to ACM or IEEE might be the right thing to do in the future when possible.
