### ISSUE TITLE
rustc-guide to rustc-dev-guide transition

### ISSUE THREAD

**Issue by chrissimpkins** [rust-lang/rustc-dev-guide#602]
The `rustc-guide` is being renamed to the `rustc-dev-guide`.  The discussion thread for this decision is https://github.com/rust-lang/rustc-guide/issues/470.

This thread is a record of the work in progress to make the transition.

- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/rustc-guide` (https://github.com/rust-lang/rustc-guide/pull/601)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/rust` (https://github.com/rust-lang/rust/pull/69747)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/blog.rust-lang.org` (https://github.com/rust-lang/blog.rust-lang.org/pull/535)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/const-eval` (https://github.com/rust-lang/const-eval/pull/37)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/compiler-team` (https://github.com/rust-lang/compiler-team/pull/254)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/rust-forge` (https://github.com/rust-lang/rust-forge/pull/314)
- [x] ~~prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/prev.rust-lang.org`~~ (not required)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/reference` (https://github.com/rust-lang/reference/pull/777)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/chalk` (https://github.com/rust-lang/chalk/pull/344)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/measureme`(https://github.com/rust-lang/measureme/pull/113)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/lang-team` (https://github.com/rust-lang/lang-team/pull/12)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/rust-clippy` (https://github.com/rust-lang/rust-clippy/pull/5277)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang-nursery/rust-lang-nursery.github.io` (https://github.com/rust-lang-nursery/rust-lang-nursery.github.io/pull/4)
- [x] prepare a PR renaming rustc-guide to rustc-dev-guide on `rust-lang/www.rust-lang.org` (https://github.com/rust-lang/www.rust-lang.org/pull/1029)
- [x] replicate the directory structure of `rust-lang/rustc-guide` to `rustc-dev-guide` in `rust-lang/rustc-guide-redirect` repo
- [x] create DNS entry for `rustc-dev-guide.rust-lang.org` to point to `rust-lang.github.io/rustc-dev-guide` @Mark-Simulacrum 
- [x] add CNAME file to repo (https://github.com/rust-lang/rustc-guide/pull/606)
- [x] update all the PRs to point links to `rustc-dev-guide.rust-lang.org` instead of `rust-lang.github.io/rustc-dev-guide`
- [x] merge all renaming PRs (notices posted on repos, IN PROGRESS)
- [x] rename repository `rust-lang/rustc-guide` to `rust-lang/rustc-dev-guide`
- [x] rename repository `rust-lang/rustc-guide-redirect` to `rust-lang/rustc-guide`
- [x] update travis CI configs as needed
- [x] adjust the description and README in *new* `rustc-guide` repository to note that the repo has migrated to `rustc-dev-guide`
- [x] update git submodule in `rust-lang/rust` (https://github.com/rust-lang/rust/pull/69898)
- [x] ~~address localizations of "rustc guide" / "Rustc Guide" on `rust-lang/www.rust-lang.org` (approach? PR https://github.com/rust-lang/www.rust-lang.org/pull/1029)~~ ([determined to be unnecessary](https://github.com/rust-lang/www.rust-lang.org/pull/1029#issuecomment-597352515))
- [x] once everything is merged check if we lack more links in https://github.com/search?p=2&q=org%3Arust-lang+rust-lang.github.io%2Frustc-guide&type=Code
    - rust (awaiting merge)
    - rust-gha (does not require updates)
    - www.rust-lang.org (does not require updates)
    - previous.rust-lang.org (does not require updates)
- [x] announce transition on Internals forum (@mark-i-m will do this)
- [x] announce transition on Inside Rust Blog (PR ready: https://github.com/rust-lang/blog.rust-lang.org/pull/537)

cc @rust-lang/wg-learning 
This work is part of the Learning WG Mar/April 2020 sprint
[Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-learning/topic/Renaming.20the.20guide)

**Comment by JohnTitor** [comment]
I don't think we need a PR for rust-gha repo.

**Comment by chrissimpkins** [comment]
Thanks @JohnTitor. I removed it from the list.

**Comment by chrissimpkins** [comment]
All renaming PR's are in place with [Do not merge yet] titles *except* for `rust-lang/prev.rust-lang.org` where the repository README indicates that it has been deprecated since 2018 and there are no commits since 2018...  I can push a PR there today if anyone feels that is a blocker.  IMO we are ready for the repository rename.

**Comment by spastorino** [comment]
> I don't think we need a PR for rust-gha repo.

why do you say so?. I found in the README a link to rustc guide which I guess should be updated? or is the information from there automatically updated from elsewhere?.

**Comment by chrissimpkins** [comment]
Added https://github.com/rust-lang-nursery/rust-lang-nursery.github.io to the rename PR list

**Comment by JohnTitor** [comment]
> why do you say so?

The repository is _only_ for testing GitHub Actions and I think it's unlikely that anyone will refer to it.

**Comment by chrissimpkins** [comment]
Added https://github.com/rust-lang/rustc-guide/issues/470#issuecomment-595680655 to the TODO list (update redirects from `rustc-guide` to `rustc-dev-guide`.  We need to locate who can do this.

**Comment by mark-i-m** [comment]
Perhaps @Mark-Simulacrum can guide us in how to set up a GH Pages site for this?

**Comment by spastorino** [comment]
I think we should:

1. rename rustc-guide to rustc-dev-guide repo
2. create a fresh rustc-guide repo
3. adjust the description and README to note that the repo has migrate to rustc-dev-guide
4. redirect all the existing links from rustc-guide to rustc-dev-guide. For that we need to recreate the directory structure of the guide with index.html files that redirect to rustc-dev-guide

**Comment by chrissimpkins** [comment]
> I think we should:
>
>1. rename rustc-guide to rustc-dev-guide repo
>2. create a fresh rustc-guide repo
>3. adjust the description and README to note that the repo has migrate to rustc-dev-guide
>4. redirect all the existing links from rustc-guide to rustc-dev-guide. For that we need to recreate the directory structure of the guide with index.html files that redirect to rustc-dev-guide

@spastorino We still need an admin for (1) - (~3).  @LeSeulArtichaut is planning to take care of (4)

**Comment by chrissimpkins** [comment]
Added Rust Internals forum notification and Inside Rust Blog notification to the TODO list (https://github.com/rust-lang/rustc-guide/issues/470#issuecomment-596135613)

**Comment by mark-i-m** [comment]
Thanks @chrissimpkins! I don't mind doing those two items, if you want to assign me

**Comment by chrissimpkins** [comment]
@mark-i-m Ty!  Assigned in the TODO list.

**Comment by mark-i-m** [comment]
Opened https://github.com/rust-lang/blog.rust-lang.org/pull/537 to be merged after the move

**Comment by chrissimpkins** [comment]
https://rustc-dev-guide.rust-lang.org/ is showing 404 pages today

cc @RalfJung

**Comment by JohnTitor** [comment]
@chrissimpkins Oops, it's my fault. I'll fix it shortly.

**Comment by JohnTitor** [comment]
Because travis doesn't have config for CNAME, they won't add it when deploying.

**Comment by chrissimpkins** [comment]
How do you work around the issue?

**Comment by JohnTitor** [comment]
Opened #608, should fix the issue.

**Comment by chrissimpkins** [comment]
@JohnTitor verified that https://rustc-dev-guide.rust-lang.org/ is fixed

**Comment by chrissimpkins** [comment]
We've moved! :)

**Comment by chrissimpkins** [comment]
Added new TODO item to address localizations of the www.rust-lang.org website.  Some of the translations are based on the "rustc guide" / "Rustc Guide" name.  PR for discussion: https://github.com/rust-lang/www.rust-lang.org/pull/1029#issuecomment-597145254

**Comment by chrissimpkins** [comment]
> Added new TODO item to address localizations of the [www.rust-lang.org](http://www.rust-lang.org) website. Some of the translations are based on the "rustc guide" / "Rustc Guide" name. See: [rust-lang/www.rust-lang.org#1029 (comment)](https://github.com/rust-lang/www.rust-lang.org/pull/1029#issuecomment-597145254)

This was [not necessary](https://github.com/rust-lang/www.rust-lang.org/pull/1029#issuecomment-597352515).  Marked as finished

**Comment by spastorino** [comment]
Marking ` once everything is merged check if we lack more links in https://github.com/search?p=2&q=org%3Arust-lang+rust-lang.github.io%2Frustc-guide&type=Code ` as done since right now it's only rust-gha and prev.rust-lang.org which we decided to not update.

**Comment by chrissimpkins** [comment]
Still waiting on https://github.com/rust-lang/rust/pull/69898 to close this.
