### ISSUE TITLE
Removal of rustc_codegen_utils breaks mdbook builds

### ISSUE THREAD

**Issue by chrissimpkins** [rust-lang/rustc-dev-guide#628]
It looks like the merge of https://github.com/rust-lang/rust/pull/69965 led to mdbook build fails on Travis: https://travis-ci.com/github/rust-lang/rustc-dev-guide/builds/154502721#L342

It is due to this link to the `librustc_codegen_utils` docs in `appendix/stupid-stats.md`:

```markdown
> NOTE: `librustc_trans` and `librustc_back` no longer exist, and we don't
> translate AST or HIR directly to LLVM IR anymore.  Instead, see
> [`librustc_codegen_llvm`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_codegen_llvm/index.html)
> and [`librustc_codegen_utils`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_codegen_utils/index.html).
```

The https://doc.rust-lang.org/nightly/nightly-rustc/rustc_codegen_utils/index.html URL lands on a 404 page.  Should it be removed or is there an updated location that still pertains here?

**Comment by mark-i-m** [comment]
@chrissimpkins `librustc_codgen_utils` has been dissolved into a bunch of places. It probably makes more sense to point to `librustc_codegen_ssa` and `librustc_codegen_llvm`.

**Comment by chrissimpkins** [comment]
I'll push a PR with the updates shortly.  Thanks Mark.

**Comment by chrissimpkins** [comment]
#630 should fix it
