### ISSUE TITLE
Broken link to no-longer-extant `has_any_child_of`

### ISSUE THREAD

**Issue by anp** [rust-lang/rustc-dev-guide#640]
[CI is failing on an unrelated part of my change](https://travis-ci.com/github/rust-lang/rustc-dev-guide/builds/156240115#L339), and it looks like the `has_any_child_of` query linked in https://github.com/rust-lang/rustc-dev-guide/blob/master/src/borrow_check/moves_and_initialization/move_paths.md#cross-references no longer exists. If it had just moved I could add a commit to my PR taking care of that but I'm not sure how to change this text to in order to reflect whatever changed to remove that query.

Halp?

**Comment by eddyb** [comment]
cc @ecstatic-morse
