### ISSUE TITLE
add instructions on how to use rustc-driver-example

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rustc-dev-guide#648]
This should help https://internals.rust-lang.org/t/using-the-rustc-interface-crate/11982/16

**Comment by mark-i-m** [comment]
@tshepang see #639 and https://rustc-dev-guide.rust-lang.org/rustc-driver.html

**Comment by tshepang** [comment]
Was getting compiler error, and realized I needed just do a...

    rustup component add rustc-dev

Instead of *use* (in the title), I should have said *run*.

**Comment by mark-i-m** [comment]
@tshepang Yeah, that got me as well! Could you open a PR to add that as a note in the `Ex: type inference through rustc_interface` chapter?

Also perhaps it makes sense to finally remove the stupid-stats appendix?

**Comment by tshepang** [comment]
yeah, stupid-stats is long overdue for removal

**Comment by mark-i-m** [comment]
@tshepang Did you want to open a PR to remove stupid-stats?

**Comment by tshepang** [comment]
@mark-i-m let me do that
