### ISSUE TITLE
Document Pattern and Exhaustiveness checking

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-dev-guide#657]
We added a skeleton chapter in #651.

cc @Centril

**Comment by Centril** [comment]
cc @arielb1 @varkor  @Nadrieril

**Comment by Nadrieril** [comment]
How detailed does that guide aim to be ? Specifically, should we move there the in-depth explanation of the exhaustiveness algorithm that is currently at the top of `_match.rs` ? Or is that too detailed ?

**Comment by Centril** [comment]
I think starting with the broad strokes, mentioning that there is an in-depth explanation, as well as linking to the paper would be a good start.

**Comment by mark-i-m** [comment]
Generally, it's a bit of judgement call. The goal is just for the guide to be a reasonable starting point for being able to contribute. Generally, that means discussion of important design decisions, data structures, routines, or algorithms, as you see fit.

Another goal is that it should avoid mentioning details that are likely to change, and link to the rustdocs for the compiler as much as possible so that we can detect changes.

**Comment by Nadrieril** [comment]
I'm finally getting around to doing this!

**Comment by jieyouxu** [comment]
Triage: #923 added high-level docs and points to doc comments in source code, we should prefer opening more specific issues for follow-ups. Closing as resolved.
