### ISSUE TITLE
Prerequisites and their setup is not documented

### ISSUE THREAD

**Issue by skade** [rust-lang/rustc-dev-guide#722]
The guide for [building rustc](https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html) does not list prerequisites.

To my reading, those are:
* python
* a C compiler toolchain
* cmake
* rustc

**Comment by arora-aman** [comment]
Probably get copy over from  https://github.com/rust-lang/rust/blob/master/README.md
