### ISSUE TITLE
Add link to Responsive compilers - Nicholas Matsakis - PLISS 2019 somewhere?

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rustc-dev-guide#778]
Just saw this talk https://www.youtube.com/watch?v=N6b44kMS6OM by Niko and I was wondering if we should include it in the guide. In general we could also have a talks section which are sometimes more entertaining than reading stuff.

cc @mark-i-m

**Comment by mark-i-m** [comment]
Also a great talk: https://www.youtube.com/watch?v=LIYkT3p5gTs

**Comment by JohnTitor** [comment]
Sounds good! Is https://rustc-dev-guide.rust-lang.org/appendix/compiler-lecture.html one of the good places? (That's more of "rustc Lecture Series" than an "Compiler Lecture Series", though.)

**Comment by spastorino** [comment]
Another two from @pnkfelix ...

[Felix Klock - Rust: A type system you didn't know you wanted - Curry On](https://www.youtube.com/watch?v=Q7lQCgnNWU0)
[Felix Klock - Subtyping in Rust and Clarke's Third Law](https://www.youtube.com/watch?v=fI4RG_uq-WU)
