### ISSUE TITLE
Documenting what "scrutinee" mean specifically

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rustc-dev-guide#796]
I see the word "scrutinee" used in Rust source, but I haven't never known its meaning.
So it is hard to remember and know when/why use that word.

**Comment by lzutao** [comment]
Oh, it is documented in Reference: <https://doc.rust-lang.org/nightly/reference/glossary.html#scrutinee>.
I don't know if there are need to keep this issue.

**Comment by JohnTitor** [comment]
I believe it'd be nice if this guide also had it.
