### ISSUE TITLE
Rename `HAIR` (High-level Abstruct IR) to `THIR` (Typed HIR) in this guide

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rustc-dev-guide#806]
Follow-up of https://github.com/rust-lang/rust/pull/74582
This proposes to rename HAIR to THIR and it'll be likely accepted.
We have some mention of HAIR here, so the follow-up work will be needed as Niko said.
I'll work on this but in case let's create an issue just as a reminder.

**Comment by LeSeulArtichaut** [comment]
Oh, no more hair puns. 😕

**Comment by mark-i-m** [comment]
In the immortal words of @Centril: "It's a HAIR cut"
