### ISSUE TITLE
Changes after std move to library

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rustc-dev-guide#817]
The first section of this chapter need to be reword: https://github.com/rust-lang/rustc-dev-guide/blob/master/src/compiler-src.md
> The main Rust repository consists of a src directory, under which there live many crates. These crates contain the sources for the standard library and the compiler. This document, of course, focuses on the latter.

Could be rewritten as:
The main Rust repository consists of two directory: `src` and `library`, under which there live many crates. 
`library` contains the sources for the standard library.
While `src` is where compiler and its components live. 
This document, of course, focuses on the latter.

**Comment by mark-i-m** [comment]
Sorry, I've been a bit swamped lately. This is on my list. There is still some change going on, especially wrt to src/librustc_*. #815 fixed a bunch of stuff.
