### ISSUE TITLE
Mention how long it takes to get code reviewed

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustc-dev-guide#837]
The Getting Started guide mentions how long it can take for bors to merge PRs, but it does not mention how long it usually takes until someone reviews a PR. It would be helpful for new contributors to see an estimation of how long it will take for someone to review their PR and after how long it is appropriate to ping. These numbers probably vary person-to-person, but it would be helpful if there were a rough estimate.

**Comment by mark-i-m** [comment]
Unfortunately, it varies a lot based on which part of the project you are working on because there will be different reviewers for different parts of the compiler -- some of them take much longer to review than others. My general rule of thumb is to ping after ~10 days of inactivity. Some reviewers (e.g. eddyb) prefer to be pinged on zulip more often than that.

I'm not really sure what the best guidance is to give here....

**Comment by camelid** [comment]
Maybe start with just saying something like:

> If you don't get a review within around 10 days, feel free to ping your reviewer on GitHub.

**Comment by Mark-Simulacrum** [comment]
I would suggest that we direct people to wg-triage on Zulip, folks there have the best awareness of when to ping and vacations and what not, as well as adding human touch which can be quite helpful here I think.

That said, I personally think adding GitHub pings that are on a different frequency than triage existing pings is harmful - most people are already pretty overloaded with pings.

**Comment by camelid** [comment]
So would you suggest saying something like this?

> If you don't get a review within around 10 days, feel free to ask the people on the `wg-triage` stream in Zulip. They have knowledge of when to ping, who's on vacation, etc.

**Comment by camelid** [comment]
Or rather, `t-release/triage`.

**Comment by Mark-Simulacrum** [comment]
Sure, though I might say "5 days" at that point. @dylan-dpc, do you feel like this is a reasonable thing for that group to field? To be clear, I wouldn't expect that we ping on all such requests (maybe even not most), just that we keep track of "author eagerness" and try to clarify expectations etc.

**Comment by Dylan-DPC** [comment]
Normally we give the reviewer at least 1 week to review pull requests (since some of them review during certain times of their weekly schedule so it goes well with that).
