### ISSUE TITLE
Add section on `@rustbot modify labels`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#855]
This is [really hard to find for new contributors](https://rust-lang.zulipchat.com/#narrow/stream/242269-t-release.2Ftriage/topic/Label.20switching.20for.20outsiders.20is.20hard): https://github.com/rust-lang/triagebot/wiki/Labeling

**Comment by camelid** [comment]
Yeah, I think I found out about it by seeing other people use it and then I found the triagebot repo wiki.

**Comment by LeSeulArtichaut** [comment]
There’s also https://forge.rust-lang.org/platforms/zulip/triagebot.html#apply-labels-to-issues

**Comment by jyn514** [comment]
That section seems like it shouldn't be under zulip. Maybe 'GitHub' would be a better place?

**Comment by jyn514** [comment]
also I don't know anywhere that links to forge, we should probably fix that.
