### ISSUE TITLE
rustaceans.org has an insecure certificate

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustc-dev-guide#868]
[rustaceans.org](https://rustaceans.org) is linked to from the dev guide [here](https://github.com/rust-lang/rustc-dev-guide/blob/91a4afbcc6bb746b9b96dadfbc3752b4f6e1c7a6/src/contributing.md#helpful-links-and-information), but visiting it produces a "security risk" or "privacy error" warning page in Firefox and Chrome. I think it's not a good experience for readers of the guide to go to a site that's linked to and get a security risk warning :/

**Comment by camelid** [comment]
Looking at the certificate, it seems this is @nrc's site.

**Comment by camelid** [comment]
It looks the issue is that the cert expired 5 days ago.

**Comment by jyn514** [comment]
nrc has [left the project](https://www.ncameron.org/blog/leaving-the-rust-core-team/) so I'm not sure who's maintaining that website ...

**Comment by camelid** [comment]
Hmm, I thought it might be his website given that the certificate is associated with his personal website. Is it not?

**Comment by nrc** [comment]
I'm still maintaining it. There's an issue open on the rustaceans repo. I plan to fix it this week. Unfortunately it is not as simple as just renewing the certificate because there is a half-finished server migration .

**Comment by camelid** [comment]
Okay, thanks @nrc!

**Comment by jyn514** [comment]
Closing in favor of https://github.com/nrc/rustaceans.org/issues/645
