### ISSUE TITLE
Profiling the Compiler

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rustc-dev-guide#88]
It would be nice to have a section on how to profile the compiler, what tools to use, how to invoke them, and maybe a section on how to interpret results.

**Comment by mark-i-m** [comment]
@michaelwoerister Is this section (and its subsections) what you were thinking of?

https://rust-lang-nursery.github.io/rustc-guide/profiling.html

**Comment by michaelwoerister** [comment]
@mark-i-m That's an excellent start! I would be great to also have some info on valgrind/cachegrind since those provide a slightly different and useful set of measurements but come with some caveats when invoking the profiler (i.e. making sure that the rustc executable is profiled, not cargo or the rustup wrapper).

**Comment by rylev** [comment]
Triage: Closing. Much like #175, this section already exists. Going to close this in favor of an issue specifically about valgrind/cachegrind.
