### ISSUE TITLE
Codegen: LLVM IR, Monomorphization, Codegen Units, Partitioning, Symbol Linkage and Visibility

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rustc-dev-guide#89]
Quite a few complicated things are going on during trans. Would be great to have it documented.

- [ ] Generating LLVM IR
    - [ ] Monomorphization
- [ ] Codegen Units
- [ ] Partitioning
- [ ] Symbol Linkage and Visibiliy

**Comment by michaelwoerister** [comment]
To clarify: the four topics in the title are relatively tightly coupled so it makes sense to treat them together.

**Comment by mark-i-m** [comment]
Definitely agree. Trans is one of the bigger missing chapters (along with type-checking, MIR construction, etc).

cc #6

**Comment by mark-i-m** [comment]
We added some skeleton chapters and have some other things in progress.
