### ISSUE TITLE
Update logging for `tracing`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rustc-dev-guide#892]
It looks like the compiler moved to the `tracing` crate. I think at a minimum, the section at https://rustc-dev-guide.rust-lang.org/compiler-debugging.html?highlight=log#getting-logging-output should be updated to mention that.

I don't actually know why it was changed, what the differences are, or what the motivation was. https://github.com/rust-lang/compiler-team/issues/331 and https://github.com/rust-lang/rust/pull/74726 don't really say.  Is there anything I need to know about the differences? Are there any examples of when using spans or `#[instrument]` would be useful? Should messages use structured fields (and how or why is that useful)?

**Comment by jyn514** [comment]
@oli-obk do you have time to work on this?

**Comment by oli-obk** [comment]
We are not using spans or `#[instrument]` yet. There are no differences in usage yet. Before we can start using awesome tracing features we'll need to benchmark them and agree on a span rendering strategy. https://github.com/rust-lang/rust/pull/75143 explores span rendering, please look at it and leave opinions.

But yea, some minimal updating of the logging section would be a good thing. I'll try to find some time, but won't complain if someone grabs it

**Comment by igaray** [comment]
I'm currently working on the survey translations but in a few days I'll free up and could take this :) Won't claim it in case someone wants to do it right away.

**Comment by camelid** [comment]
I fixed this in #997.
