### ISSUE TITLE
Explain what `Assemble` does in bootstrap

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#911]
I am not actually sure what this does. It can't just be copying files because I tried running the binary in stage0-rustc and it gave an error about shared objects:
```
build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/rustc-main: error while loading shared libraries: librustc_driver-3b0ece280f85df92.so: cannot open shared object file: No such file or directory
```

_Originally posted by @jyn514 in https://github.com/rust-lang/rustc-dev-guide/pull/857#r498534586_

**Comment by Mark-Simulacrum** [comment]
It just copies files. You get linker errors otherwise because cargo directory layout doesn't match our rpath (../lib iirc)
