### ISSUE TITLE
Document stabilization PRs for the standard library

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#932]
Right now https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr is very geared towards the compiler itself. We should document what a stabilization PR looks like for the standard library. Info here: https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/const.20alloc.3A.3ALayout and example PR: https://github.com/rust-lang/rust/pull/75132

I'm imagining this as a separate page from `stabilization_guide` to make it easier to find in the table of contents, but I'm not super tied to that.

**Comment by m-ou-se** [comment]
This missing documentation caused more confusion yet again in https://github.com/rust-lang/rust/issues/73831.

We should fix this. (:

**Comment by m-ou-se** [comment]
Our most up-to-date info on this is: https://raw.githubusercontent.com/rust-lang/rust/master/.github/ISSUE_TEMPLATE/library_tracking_issue.md

**Comment by KodrAus** [comment]
There's nothing there yet, but we do have a repo now that we should definitely document this in: https://github.com/rust-lang/std-dev-guide
