### ISSUE TITLE
Switch from Travis CI to GHA?

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rustc-dev-guide#940]
See https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/RIP.20travis and https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing :(

**Comment by rylev** [comment]
Would switching effect the number of runners that can be used by rust-lang/rust? I wasn't sure if runners were partitioned by org or by repo. I'd be happy to do this if people think it would be an improvement.

**Comment by JohnTitor** [comment]
@rylev IIRC the limit on the number of jobs is divided between rust-lang/rust and the rest (that's why we have the rust-lang-ci org), and the number is enough to use GHA here. There's no concern for a while so I think it's okay to go ahead, I'm happy to review a PR :)
