### ISSUE TITLE
Document using download-rustc for working on rustdoc

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#942]
This is the easy part of https://github.com/rust-lang/rust/issues/66581. It should go in `rustdoc.html`.

**Comment by jyn514** [comment]
I think to close this, we'd just need to add an `x setup tools` snippet to the start of https://rustc-dev-guide.rust-lang.org/rustdoc.html.

**Comment by jieyouxu** [comment]
Triage: cheat sheet does have this snippet now.
