### ISSUE TITLE
Document optimization fuel for MIR optimizations

### ISSUE THREAD

**Issue by cjkenn** [rust-lang/rustc-dev-guide#962]
[This](https://github.com/rust-lang/rust/issues/77402#issuecomment-702248513) comment suggests adding some docs for optimization fuel usage. I agree with that sentiment, so now that https://github.com/rust-lang/rust/pull/79117 is merged I figure we can whip up a quick explanation for the change and why optimization fuels is used.

I'll write these docs, just wanted to make this issue in case it's needed for tracking purposes.

**Comment by jyn514** [comment]
@cjkenn thanks for working on this! In general there's no need to open an issue if you're going to immediately open a PR, I normally use issues for things I don't have time for at the moment.
