### ISSUE TITLE
Document how to use gdb on rustc itself

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-dev-guide#965]
This requires me to first figure out how to do it; I know how for standalone files but I tried and failed to do this when compiling the standard library.

**Comment by camelid** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/how.20to.20run.20gdb.20on.20rustc.3F

**Comment by igaray** [comment]
Also see #443 if you haven't, possible duplicate issue.

**Comment by jyn514** [comment]
Yup, thanks.
